src/Entity/Piece.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\PieceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PieceRepository::class)
 * @ApiResource()
 */
class Piece
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=typePiece::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_type_piece;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix_vente;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\ManyToOne(targetEntity=fournisseur::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $fournisseur;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite_stock;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix_catalogue;

    /**
     * @ORM\ManyToOne(targetEntity=Composition::class, inversedBy="piece_composante")
     */
    private $composition;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdTypePiece(): ?typePiece
    {
        return $this->id_type_piece;
    }

    public function setIdTypePiece(?typePiece $id_type_piece): self
    {
        $this->id_type_piece = $id_type_piece;

        return $this;
    }

    public function getPrixVente(): ?float
    {
        return $this->prix_vente;
    }

    public function setPrixVente(?float $prix_vente): self
    {
        $this->prix_vente = $prix_vente;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getFournisseur(): ?fournisseur
    {
        return $this->fournisseur;
    }

    public function setFournisseur(?fournisseur $fournisseur): self
    {
        $this->fournisseur = $fournisseur;

        return $this;
    }

    public function getQuantiteStock(): ?int
    {
        return $this->quantite_stock;
    }

    public function setQuantiteStock(int $quantite_stock): self
    {
        $this->quantite_stock = $quantite_stock;

        return $this;
    }

    public function getPrixCatalogue(): ?float
    {
        return $this->prix_catalogue;
    }

    public function setPrixCatalogue(?float $prix_catalogue): self
    {
        $this->prix_catalogue = $prix_catalogue;

        return $this;
    }

    public function getComposition(): ?Composition
    {
        return $this->composition;
    }

    public function setComposition(?Composition $composition): self
    {
        $this->composition = $composition;

        return $this;
    }
}

src/Form/PieceType.php
<?php

namespace App\Form;

use App\Entity\Piece;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PieceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prix_vente')
            ->add('libelle')
            ->add('quantite_stock')
            ->add('prix_catalogue')
            ->add('id_type_piece')
            ->add('fournisseur')
            ->add('composition')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Piece::class,
        ]);
    }
}

src/Controller/PieceController.php
<?php

namespace App\Controller;

use App\Entity\Piece;
use App\Form\PieceType;
use App\Repository\PieceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/piece")
 */
class PieceController extends AbstractController
{
    /**
     * @Route("/", name="piece_index", methods={"GET"})
     */
    public function index(PieceRepository $pieceRepository): Response
    {
        return $this->render('piece/index.html.twig', [
            'pieces' => $pieceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="piece_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $piece = new Piece();
        $form = $this->createForm(PieceType::class, $piece);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($piece);
            $entityManager->flush();

            return $this->redirectToRoute('piece_index');
        }

        return $this->render('piece/new.html.twig', [
            'piece' => $piece,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="piece_show", methods={"GET"})
     */
    public function show(Piece $piece): Response
    {
        return $this->render('piece/show.html.twig', [
            'piece' => $piece,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="piece_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Piece $piece): Response
    {
        $form = $this->createForm(PieceType::class, $piece);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('piece_index');
        }

        return $this->render('piece/edit.html.twig', [
            'piece' => $piece,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="piece_delete", methods={"POST"})
     */
    public function delete(Request $request, Piece $piece): Response
    {
        if ($this->isCsrfTokenValid('delete'.$piece->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($piece);
            $entityManager->flush();
        }

        return $this->redirectToRoute('piece_index');
    }
}

templates/piece/_delete_form.html.twig
<form method="post" action="{{ path('piece_delete', {'id': piece.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ piece.id) }}">
    <button class="btn">Delete</button>
</form>

templates/piece/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/piece/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Piece{% endblock %}

{% block body %}
    <h1>Edit Piece</h1>

    {{ include('piece/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('piece_index') }}">back to list</a>

    {{ include('piece/_delete_form.html.twig') }}
{% endblock %}

templates/piece/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Piece index{% endblock %}

{% block body %}
    <h1>Piece index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prix_vente</th>
                <th>Libelle</th>
                <th>Quantite_stock</th>
                <th>Prix_catalogue</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for piece in pieces %}
            <tr>
                <td>{{ piece.id }}</td>
                <td>{{ piece.prixVente }}</td>
                <td>{{ piece.libelle }}</td>
                <td>{{ piece.quantiteStock }}</td>
                <td>{{ piece.prixCatalogue }}</td>
                <td>
                    <a href="{{ path('piece_show', {'id': piece.id}) }}">show</a>
                    <a href="{{ path('piece_edit', {'id': piece.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('piece_new') }}">Create new</a>
{% endblock %}

templates/piece/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Piece{% endblock %}

{% block body %}
    <h1>Create new Piece</h1>

    {{ include('piece/_form.html.twig') }}

    <a href="{{ path('piece_index') }}">back to list</a>
{% endblock %}

templates/piece/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Piece{% endblock %}

{% block body %}
    <h1>Piece</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ piece.id }}</td>
            </tr>
            <tr>
                <th>Prix_vente</th>
                <td>{{ piece.prixVente }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ piece.libelle }}</td>
            </tr>
            <tr>
                <th>Quantite_stock</th>
                <td>{{ piece.quantiteStock }}</td>
            </tr>
            <tr>
                <th>Prix_catalogue</th>
                <td>{{ piece.prixCatalogue }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('piece_index') }}">back to list</a>

    <a href="{{ path('piece_edit', {'id': piece.id}) }}">edit</a>

    {{ include('piece/_delete_form.html.twig') }}
{% endblock %}